"""HTML report sink (DF-309) — one self-contained file, no CDN, no build step, no JS.

The first visual output, and it lands now for a reason: a single run is a list (terminals
render that well), but a compare run is a matrix of models × cases (terminals render that
badly). The data finally justifies the format.

Hard constraints (SPEC §9, ARCHITECTURE §11):
  - **One self-contained file.** All CSS is inlined; there are no external assets, no
    fonts, no scripts. It opens from `file://` with the network disabled — an air-gapped
    CI artifact is a real use case. Expandable detail uses native `<details>`/`<summary>`,
    so **no JavaScript is needed**.
  - **No server, ever.** This is a file, not `dryfire ui`.
  - **Semantic HTML first, styling second** — it is fully legible with CSS disabled.

On the template: the shell + CSS is a module constant, not a separate packaged file, on
purpose. A self-contained artifact that must survive `uvx dryfire` cannot risk a template
being dropped from the wheel — a failure that would surface only after publish, invisible
to source-tree tests. A `.py` constant always ships.

The failure view is the priority: full trajectory, tool arguments, assertion messages, and
judge reasoning where present — the turn-by-turn detail that would flood a console.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from html import escape

from dryfire.application.scheduler import CaseResult, RunResult
from dryfire.application.usecases.compare import CompareColumn, CompareResult

# -- The self-contained shell (inlined CSS, no external anything) ------------

_CSS = """
:root { --pass:#1a7f37; --fail:#cf222e; --warn:#9a6700; --bg:#fff; --fg:#1f2328;
        --muted:#656d76; --line:#d0d7de; --panel:#f6f8fa; }
* { box-sizing:border-box; }
body { margin:0; padding:2rem; background:var(--bg); color:var(--fg);
       font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif; }
h1 { font-size:1.4rem; margin:0 0 .25rem; } h2 { font-size:1.1rem; margin:2rem 0 .5rem; }
.meta { color:var(--muted); margin-bottom:1.5rem; }
.summary { display:flex; gap:1.5rem; flex-wrap:wrap; padding:.75rem 1rem; background:var(--panel);
           border:1px solid var(--line); border-radius:6px; margin-bottom:1rem; }
.pass { color:var(--pass); } .fail { color:var(--fail); } .warn { color:var(--warn); }
details { border:1px solid var(--line); border-radius:6px; margin:.4rem 0; background:var(--bg); }
details[open] { background:var(--panel); }
summary { cursor:pointer; padding:.5rem .75rem; font-weight:600; list-style:none; }
summary::-webkit-details-marker { display:none; }
summary .name { font-family:ui-monospace,SFMono-Regular,Menlo,monospace; }
.detail { padding:0 .75rem .75rem; }
.assertion { margin:.35rem 0; padding:.4rem .6rem; border-left:3px solid var(--line); }
.assertion.bad { border-left-color:var(--fail); background:#fff5f5; }
.msg { font-family:ui-monospace,SFMono-Regular,Menlo,monospace; white-space:pre-wrap;
       color:var(--fail); font-size:.85rem; }
.turn { border-top:1px solid var(--line); padding:.5rem 0; }
.turn .role { color:var(--muted); font-size:.8rem; text-transform:uppercase; letter-spacing:.03em; }
pre { font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:.85rem;
      white-space:pre-wrap; word-break:break-word; margin:.25rem 0; }
.judge { border-left:3px solid var(--warn); padding:.4rem .6rem; margin:.35rem 0;
         background:#fffbe6; }
table { border-collapse:collapse; width:100%; margin:.5rem 0; }
th,td { border:1px solid var(--line); padding:.4rem .6rem; text-align:left; }
td.cell { text-align:center; font-family:ui-monospace,monospace; }
tr.disagree { background:#fffbe6; }
tr.disagree td:first-child::before { content:"~ "; color:var(--warn); font-weight:700; }
.footer { color:var(--muted); font-size:.8rem; margin-top:2rem; }
"""

_SHELL = (
    "<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>__TITLE__</title>\n<style>__CSS__</style>\n</head>\n<body>\n__BODY__\n"
    "<p class=\"footer\">Generated by dryfire — self-contained, no network required.</p>\n"
    "</body>\n</html>\n"
)


def _document(title: str, body: str) -> str:
    return (
        _SHELL.replace("__CSS__", _CSS)
        .replace("__TITLE__", escape(title))
        .replace("__BODY__", body)
    )


def _iso(moment: datetime) -> str:
    return moment.astimezone(UTC).isoformat(timespec="seconds").replace("+00:00", "Z")


# -- Run report -------------------------------------------------------------


def render_run_html(run: RunResult, *, generated_at: datetime) -> str:
    """A full run as one self-contained HTML page. Failing cases render open with their
    turn-by-turn detail; passing cases are collapsed."""
    cases = [c for suite in run.suites for c in suite.cases]
    passed = sum(1 for c in cases if c.passed)
    failed = len(cases) - passed
    body = [
        "<h1>dryfire run report</h1>",
        f"<p class=\"meta\">{escape(_iso(generated_at))}</p>",
        "<div class=\"summary\">"
        f"<span>{len(cases)} cases</span>"
        f"<span class=\"pass\">{passed} passed</span>"
        f"<span class=\"fail\">{failed} failed</span>"
        f"{'' if run.complete else '<span class=\"warn\">incomplete (fail-fast)</span>'}"
        "</div>",
    ]
    for suite in run.suites:
        body.append(f"<h2>{escape(suite.name)}</h2>")
        for case in suite.cases:
            body.append(_case_html(case))
    return _document("dryfire run report", "\n".join(body))


def _case_html(case: CaseResult) -> str:
    glyph = "✓" if case.passed else "✗"
    cls = "pass" if case.passed else "fail"
    rate = ""
    if case.repetitions is not None:  # a repeated case (DF-305)
        rate = f" <span class=\"warn\">{case.passes}/{case.total}</span>"
    parts = [
        f"<details{'' if case.passed else ' open'}>",
        f"<summary class=\"{cls}\">{glyph} "
        f"<span class=\"name\">{escape(case.case_name)}</span>{rate}</summary>",
        "<div class=\"detail\">",
    ]
    if case.error:
        parts.append(f"<p class=\"msg\">{escape(case.error)}</p>")
    for a in case.assertions:
        bad = " bad" if not a.passed else ""
        parts.append(f"<div class=\"assertion{bad}\">{escape(a.description)}")
        if not a.passed and a.message:
            parts.append(f"<div class=\"msg\">{escape(a.message)}</div>")
        parts.append("</div>")
    if case.trace is not None:
        parts.append(_trace_html(case))
    parts.append("</div></details>")
    return "\n".join(parts)


def _trace_html(case: CaseResult) -> str:
    trace = case.trace
    assert trace is not None
    parts: list[str] = []
    for verdict in trace.judge_verdicts.values():
        note = f" — {escape(verdict.error)}" if verdict.error else ""
        parts.append(
            f"<div class=\"judge\"><strong>llm_judge</strong> "
            f"score {verdict.score:g} / threshold {verdict.threshold:g}{note}"
            f"<div class=\"msg\">{escape(verdict.reasoning)}</div></div>"
        )
    for turn in trace.turns:
        parts.append(f"<div class=\"turn\"><div class=\"role\">turn {turn.index}</div>")
        for message in turn.request_messages:
            parts.append(f"<pre>[{escape(message.role)}] {escape(str(message.content))}</pre>")
        if turn.response.text:
            parts.append(f"<pre>{escape(turn.response.text)}</pre>")
        for call in turn.response.tool_calls:
            parts.append(f"<pre>→ {escape(call.name)}({escape(json.dumps(call.arguments))})</pre>")
        for result in turn.tool_results:
            flag = " [error]" if result.is_error else ""
            parts.append(f"<pre>← tool_result{flag}: {escape(str(result.content))}</pre>")
        parts.append("</div>")
    parts.append(f"<p class=\"meta\">termination: {escape(trace.termination)}</p>")
    return "\n".join(parts)


# -- Compare report ---------------------------------------------------------


def render_compare_html(result: CompareResult, *, generated_at: datetime) -> str:
    """A compare matrix as one self-contained HTML page — the shareable artifact, in the
    format (a table) HTML actually renders well."""
    columns = result.columns
    rows = _compare_rows(columns)
    header = "".join(f"<th>{escape(c.label)}</th>" for c in columns)
    body = [
        "<h1>dryfire compare report</h1>",
        f"<p class=\"meta\">{escape(_iso(generated_at))} — "
        f"{len(columns)} {escape(result.axis)}s × {len(rows)} cases</p>",
        "<table><thead><tr><th>case</th>" + header + "</tr></thead><tbody>",
    ]
    for case_name in rows:
        verdicts = [_compare_verdict(c, case_name) for c in columns]
        present = [v for v in verdicts if v is not None]
        disagree = len(set(present)) > 1
        cells = "".join(
            f"<td class=\"cell {_cell_cls(v)}\">{_cell_glyph(v)}</td>" for v in verdicts
        )
        tr = " class=\"disagree\"" if disagree else ""
        body.append(f"<tr{tr}><td>{escape(case_name)}</td>{cells}</tr>")
    body.append("</tbody><tfoot>")
    body.append("<tr><td>pass rate</td>"
                + "".join(f"<td class=\"cell\">{_metric_rate(c)}</td>" for c in columns) + "</tr>")
    body.append("<tr><td>cost</td>"
                + "".join(f"<td class=\"cell\">{_metric_cost(c)}</td>" for c in columns) + "</tr>")
    body.append("<tr><td>mean latency</td>"
                + "".join(f"<td class=\"cell\">{_metric_latency(c)}</td>" for c in columns)
                + "</tr>")
    body.append("</tfoot></table>")
    return _document("dryfire compare report", "\n".join(body))


def _compare_rows(columns: list[CompareColumn]) -> list[str]:
    for col in columns:
        if col.run is not None:
            return [c.case_name for suite in col.run.suites for c in suite.cases]
    return []


def _compare_verdict(col: CompareColumn, case_name: str) -> bool | None:
    if col.run is None:
        return None
    for suite in col.run.suites:
        for c in suite.cases:
            if c.case_name == case_name:
                return c.passed
    return None


def _cell_glyph(v: bool | None) -> str:
    return "✓" if v else "✗" if v is False else "·"


def _cell_cls(v: bool | None) -> str:
    return "pass" if v else "fail" if v is False else "warn"


def _metric_rate(col: CompareColumn) -> str:
    return "FAILED" if col.metrics is None else f"{col.metrics.pass_rate:.0%}"


def _metric_cost(col: CompareColumn) -> str:
    if col.metrics is None or col.metrics.total_cost_usd is None:
        return "—"
    return f"${col.metrics.total_cost_usd:.4f}"


def _metric_latency(col: CompareColumn) -> str:
    return "—" if col.metrics is None else f"{col.metrics.mean_latency_ms:.0f}ms"
